spring.config.import=optional:file:${user.dir}/.env[.properties],optional:file:${user.dir}/demo/.env[.properties],optional:file:./.env[.properties],optional:file:.env[.properties]
server.port=8082
spring.application.name=restaurant_service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=${JWT_SIGNER_KEY}
